name: ubbottleapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# version: 2.1.3+2103
version: 11.4.03+91

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_icon: ^0.0.5
  animated_splash_screen: ^1.3.0
  back_button_interceptor: ^8.0.3
  # background_location: ^0.13.2
  badges: ^3.1.2
  build_runner: ^2.4.6
  uuid: ^4.5.1
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  pinput: ^6.0.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_downloader: ^1.11.6
  flutter_easyloading: ^3.0.5
  flutter_file_downloader: ^2.0.0
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^19.2.1
  #  flutter_logs: ^2.1.12
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_switch: ^0.3.2
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.5.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_storage: ^2.1.1
  get: ^4.6.6
  google_fonts: ^8.0.0
  google_sign_in: ^7.2.0
  hexcolor: ^3.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  json_serializable: ^6.7.1
  loading_overlay: ^0.5.0
  local_auth: ^3.0.0
  material_icons_named: ^3.16.0
  # open_file_plus: ^3.4.1+1
  otp_text_field: ^1.1.3
  package_info_plus: ^8.1.3
  permission_handler: ^12.0.0+1
  # platform_device_id: ^1.0.1
  # platform_device_id: ^1.0.1
  lottie:
  #  qr_code_scanner: ^1.0.1
  #  scan: ^1.6.0
  #  flutter_barcode_scanner: ^2.0.0
  mobile_scanner:
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  syncfusion_flutter_calendar:
  syncfusion_flutter_charts:
  text_scroll: ^0.2.0
  timeline_tile: ^2.0.0
  simple_icons: ^14.6.1
  auto_size_text: ^3.0.0
  flutter_typeahead: ^5.2.0
  substring_highlight: ^1.0.33
  location:
  file_downloader_flutter: ^0.0.5
  cupertino_icons: ^1.0.8
  bottom_picker: ^4.1.1
  #  simple_downloader: ^0.0.3+1
  flutter_swipe_button: ^2.1.3
  background_location_tracker: ^1.4.3
  google_maps_flutter: ^2.10.0
  animate_do: ^4.2.0
  easy_stepper: ^0.9.1
  timeago: ^3.7.0
  #  flutter_local_network_ios: ^0.0.1
  flutter_expanded_tile: ^0.4.0
  app_settings: ^7.0.0
  file_picker: ^10.3.8
  flutter_image_compress: ^2.4.0
  change_app_package_name: ^1.5.0
  open_file: ^3.5.11
  # board_datetime_picker: ^2.2.0
  # gradient_circular_progress_indicator: ^0.0.4
  # syncfusion_flutter_datepicker: ^28.1.35
  # platform_device_id_plus: 1.0.5
  # platform_device_id:
  # git:
  #   url: https://github.com/faridfedora/platform_device_id_kotlin_updated.git
  #   ref: master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ub_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  #  web:
  #    generate: true
  #    image_path: "images/agilelabslogo.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
    - assets/lotties/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Gellix
      fonts:
        - asset: assets/fonts/Gellix-Black.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf

#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
